@startuml
skinparam groupInheritance 2
top to bottom direction

class DrawingApp {
	+ {static} main(args : [String]) : void
}

DrawingApp *--> org.anttijuustila.drawingdemo.controller.DrawingDocument
DrawingApp ..> javax.swing.JFrame
javax.swing.JFrame *--> org.anttijuustila.drawingdemo.view.DrawingPanel
javax.swing.JFrame *--> org.anttijuustila.drawingdemo.view.ListPanel

package org.anttijuustila.drawingdemo {

	package controller {
		class DrawingDocument {
			+ addObserver(observer: DocumentObserver)
			+ removeObserver(observer: DocumentObserver)
			+ createShape() : DrawingShape
			+ getShapes() : List<DrawingShape>
			+ setSelectedShape(whichShape : int)
			+ removeShape(selectedIndex: int)
		}
		interface DocumentObserver {
			+ documentChanged()
			+ selectionChanged(selection : int)
		}
		DrawingDocument *--> DocumentObserver : observers
		DrawingDocument *--> org.anttijuustila.drawingdemo.model.DrawingShape : shapes
	}

	package model {
		class DrawingShape
	}

	package view {
		class ListPanel {
			- elementList : javax.swing.JList<DrawingShape>
			+ valueChanged(e : ListSelectionEvent)
			+ keyReleased(e : KeyEvent) 
		}
		ListPanel ..|> DocumentObserver
		ListPanel ..> DrawingDocument
		ListPanel ..|> javax.swing.JPanel
		class DrawingPanel {
			+ paintComponent(g : Graphics)
			+ mousePressed(e : MouseEvent)
			+ mouseReleased(e : MouseEvent)
			+ mouseDragged(e : MouseEvent)
		}
		DrawingPanel ..|> DocumentObserver
		DrawingPanel ..|> javax.swing.JPanel
		DrawingPanel ..> DrawingDocument
		class DrawingElementListModel
		ListPanel *--> DrawingElementListModel
		DrawingElementListModel ..> org.anttijuustila.drawingdemo.controller.DrawingDocument
		DrawingElementListModel --|> javax.swing.AbstractListModel
	}

}
@enduml